unstable_features = true
max_width = 135
comment_width = 135
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"
condense_wildcard_suffixes = true
fn_args_density = "Compressed"
fn_single_line = true
where_single_line = true
merge_imports = true
normalize_comments = true
newline_style = "unix"
brace_style = "PreferSameLine"
edition = "2018"