/* automatically generated by rust-bindgen 0.54.1 */

#![allow(dead_code)]
use enigma_types::*;
use sgx_types::*;

extern "C" {
    pub fn ocall_save_to_memory(
        retval: *mut u64,
        data_ptr: *const u8,
        data_len: size_t,
    ) -> sgx_status_t;
}
