[package]
name = "contract"
version = "0.1.0"
edition = "2018"

[dependencies]
eng-wasm = "0.1"
eng-wasm-derive = "0.1"

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"